{% set version = "2023d" %}

package:
  name: tzdata
  version: {{ version }}

source:
  - url: https://data.iana.org/time-zones/releases/tzdata{{ version }}.tar.gz
    sha256: dbca21970b0a8b8c0ceceec1d7b91fa903be0f6eca5ae732b5329672232a08f3
  - url: https://data.iana.org/time-zones/releases/tzcode{{ version }}.tar.gz
    sha256: e9a5f9e118886d2de92b62bb05510a28cc6c058d791c93bd6b84d3292c3c161e

build:
  number: 0
  noarch: generic
  # The recipe assumes building on Linux, but we don't have "skip" active since
  # the linter will complain with "`noarch` packages can't have selectors".
  # skip: True  # [not linux]
  ignore_run_exports:
    - libgcc-ng

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - make
  host:
  run:

test:
  commands:
    - test -f "${PREFIX}/share/zoneinfo/leapseconds"
    - test -f "${PREFIX}/share/zoneinfo/iso3166.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone1970.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone.tab"
    - test -f "${PREFIX}/share/zoneinfo/tzdata.zi"
    # Make sure we only package zoneinfo and nothing else.
    - |
      dirs="$(
        find "${PREFIX}" -mindepth 1 -maxdepth 2 \
        \! -path "${PREFIX}/share" \! -path "${PREFIX}/conda-meta*"
      )"
      test "${dirs}" = "${PREFIX}/share/zoneinfo"
    # Make sure we only package timezone information files.
    - |
      heads="$(
        find "${PREFIX}/share/zoneinfo" -type f \
          \! -name \*.zi \! -name \*.tab \! -name leapseconds \
          -exec head -c4 {} \; -printf \\n \
          | uniq
      )"
      test "${heads}" = TZif

about:
  home: https://www.iana.org/time-zones
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  license: LicenseRef-Public-Domain
  license_file: LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo) data

  description: |
    The Time Zone Database (called tz, tzdb or zoneinfo) contains code 
    (the tzcode package) and data (this package) that represent the
    history of local time for many representative
    locations around the globe.  It is updated periodically to reflect
    changes made by political bodies to time zone boundaries, UTC offsets,
    and daylight-saving rules.

extra:
  recipe-maintainers:
    - ocefpaf
    - mbargull
    - pganssle
